### ISSUE TITLE
Code for embedding graph in a metric?

### ISSUE THREAD

**Issue by verejoel** [USFDataVisualization/PersistentHomologyOnGraphs#1]
Thank you for making this great project available!

I have some (unweighted) graphs I have generated from datasets, and would like to ask if you have any recommendations for how to embed them in a metric space?

In the paper you mention calculating the Jaccard index between points to determine the weights.  I also see that in your data, each node has an x and y coordinate - could you give some details on how this is calculated?

Do you know if a package exists that can take my unweighted graphs and produce data ready to feed into this program?

Thanks!

**Comment by PaulRosenPhD** [comment]
Hi Joel,

Thanks for reaching out.

I have some (unweighted) graphs I have generated from datasets, and would like to ask if you have any recommendations for how to embed them in a metric space?

This is not necessarily an easy question to answer. In the case of our software, it will do it for you using short path on the Jaccard index. More generally though, it is highly dependent upon what “structure” you want to find in the graph. If you have some more information about what your data is and what you’d like to see, I can provide suggestions.


In the paper you mention calculating the Jaccard index between points to determine the weights.

The Jaccard index is calculated inside of our software, so you don’t need to do anything to use that (besides clicking a few buttons).


I also see that in your data, each node has an x and y coordinate - could you give some details on how this is calculated?

The x and y in the datasets are actually the output of our software. If you have a new dataset to input, you don’t need to specify those values. They will be calculated when the graph is loaded.


Do you know if a package exists that can take my unweighted graphs and produce data ready to feed into this program?

Off the top of my head, the best bet would be to use python. To be honest, I didn’t prep the data, the student on the paper did most of that work. She would be a better person to get in touch with on the best way to do that, and I’m sure she’d be happy to guide you through whatever precess she used.

   Ashley Suh
   https://www.eecs.tufts.edu/~asuh/
   ashley.suh@tufts.edu<mailto:ashley.suh@tufts.edu>

If you have any more questions, don’t hesitate to ask!

Cheers,
Paul

====================================
Paul Rosen, Ph.D.
Assistant Professor
Computer Science and Engineering
University of South Florida
prosen@usf.edu<mailto:prosen@usf.edu>
http://www.cspaul.com



On Aug 22, 2019, at 7:42 AM, Joel Verezhak <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for making this great project available!

I have some (unweighted) graphs I have generated from datasets, and would like to ask if you have any recommendations for how to embed them in a metric space?

In the paper you mention calculating the Jaccard index between points to determine the weights. I also see that in your data, each node has an x and y coordinate - could you give some details on how this is calculated?

Do you know if a package exists that can take my unweighted graphs and produce data ready to feed into this program?

Thanks!

**Comment by verejoel** [comment]
Hi Paul,

thanks so much for your detailed response.

I am working with topological networks generated using the Mapper algorithm on point-cloud data, and looking for interesting ways to visualise the output.  So I really like how the persistent homology of the graph is driving segmentation in your solution.

I'll keep playing with some of my own data and report back any issues I find.

All the best,

Joel
